export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ONE_ITEM: 'DELETE_ONE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
    MERGE_CART_WITH_FIRE_BASE: 'MERGE_CART_WITH_FIRE_BASE'
};
