const FavoriteActiontypes = { 
    ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
    REMOTE_FROM_FAVORITE: 'REMOTE_FROM_FAVORITE',
    REMOVE_ALL_FROM_FAVORITE: 'REMOVE_ALL_FROM_FAVORITE',
    TOGGLE_FAVORITE_ITEM: 'TOGGLE_FAVORITE_ITEM'
};

export default FavoriteActiontypes;